AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  BinanceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: binance-dependencies
      Description: Layer containing python-binance dependency
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  BinanceExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: binance_export/
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::274076144467:role/daily-binance-export-role
      Layers:
        - !Ref BinanceLayer
        - arn:aws:lambda:eu-central-1:336392948345:layer:AWSSDKPandas-Python311:3
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
